### REGISTER 
POST http://localhost:4000/api/auth/register
Content-Type: application/json
{
  "firstName": "Stevan9",
  "lastName": "Stevanovic9",
  "email": "stevans939@gmail.com",
  "password": "312392"
}

### LOGIN 
POST http://localhost:4000/api/auth/login
Content-Type: application/json
{
  "email": "stevans9311@gmail.com",
  "password": "312392"
}